version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/workers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/installer"
    schedule:
      interval: "monthly"
