name = "auto-coursera-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
EXTENSION_ID = "alojpdnpiddmekflpagdblmaehbdfcge"
CURRENT_VERSION = "1.7.5"
ALLOWED_ORIGIN = "https://autocr.nicx.me"
CDN_BASE_URL = "https://cdn.autocr.nicx.me"

[[r2_buckets]]
binding = "EXTENSIONS_BUCKET"
bucket_name = "extensions-bucket"

[[r2_buckets]]
binding = "RELEASES_BUCKET"
bucket_name = "releases-bucket"

[env.production]
routes = [
  { pattern = "api.autocr.nicx.me/*", zone_name = "nicx.me" }
]
